export class stlphysicalpuritymodel{
  id : number;
  stl_physical_purity_test_no : string;
  process_transfer_no : string;
  crop_code : string;
  item_no : string;
  item_name : string;
  lot_no : string;
  sample_code : string;
  stage_code : string;
  arrival_qty : number;
  location_code : number;
  created_by : string
  created_on : string;
  pure_seed_per : number;
  inert_matter_per : number;
  cut_seed_per : number;
  other_crop_seed_per : number;
  objectional_weed_seed_per : number;
  insect_damage_per : number;
  other_disting_seed_per : number;
  pure_seed_res : string;
  inert_matter_res : string;
  cut_seed_res : string;
  other_crop_seed_res : string;
  objectional_weed_seed_res : string;
  insect_damage_res : string;
  other_disting_seed_res : string;
  ocs : number;
  ws : number;
  odv : number;
  inert_matter : number;
  final_res : string;
  result_date : string;
  result_done : number;
  result_done_by : string;
  sub_cat_name : string;
  crop_type : string;
  class_of_seed : string;
}

